name: ML CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # -----------------------------
      # CHECKOUT
      # -----------------------------
      - name: Checkout Repo
        uses: actions/checkout@v3

      # -----------------------------
      # PYTHON SETUP
      # -----------------------------
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # -----------------------------
      # INSTALL DEPENDENCIES
      # -----------------------------
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # -----------------------------
      # TRAIN MODEL
      # -----------------------------
      - name: Train Model
        run: python src/train.py

      # -----------------------------
      # EVALUATE MODEL (CI GATE)
      # -----------------------------
      - name: Evaluate Model
        run: python src/evaluate.py

      # -----------------------------
      # BUILD DOCKER IMAGE
      # -----------------------------
      - name: Build Docker Image
        run: docker build -t churn-api:latest .

      # -----------------------------
      # RUN CONTAINER + DEBUG + HEALTH CHECK
      # -----------------------------
      - name: Run Container & Health Check
        run: |
          echo "Starting container..."
          docker run -d -p 8000:8000 --name churn-test churn-api:latest || true

          echo "Waiting for API to boot..."
          sleep 12

          echo "========== CONTAINER STATUS =========="
          docker ps -a || true

          echo "========== CONTAINER LOGS =========="
          docker logs churn-test || true
            
          echo "========== HEALTH CHECK =========="
          curl --fail http://localhost:8000/health